services:
  - type: web
    name: zoe-chatbot
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: zoe-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: WASSENGER_API_KEY
        sync: false
      - key: WASSENGER_DEVICE_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FIELD_ENCRYPTION_KEY
        generateValue: true

databases:
  - name: zoe-db
    plan: free
